#!/bin/sh

#! SELinux Policy Editor, a simple editor for SELinux policies
#! Copyright (C) 2006 Yuichi Nakamura

SETFILES=/usr/sbin/setfiles

while read LINE
do
    if [ ! -e $LINE ]
    then
	echo "$LINE does not exist, skipped"
	continue 
    fi
	$SETFILES ./sepolicy/file_contexts $LINE -v
done

